### PR TITLE
Update all licenses to OpenJS recommendation

### PR DESCRIPTION
**Pull request by chrisgervang**
For #2467

### CODE REVIEW

**Comment by chrisgervang** [comment]
Going to fix my DCO

**Review by ibgreen — COMMENTED** [review]
Worth a bullet in the "whats new" docs section? Wherever that is?

**Comment by ibgreen** [comment]
> Going to fix my DCO 

No need to close PR, just squash to single commit and do `git commit --amend --signoff`?

**Comment by chrisgervang** [comment]
Thanks, I hadn't set up GPG. Let's use #2471

**Pull request closed without merging**
