### PR TITLE
Fix #579

### LINKED ISSUE #579: [Bug][Jupyter Widget] Python 3 compatibility?
**Describe the bug**
Jupyter widget for Kepler does not seem to work under Python 3

**To Reproduce**
1. Using the following `Dockerfile`

```Dockerfile
FROM darribas/gds:2.0

RUN pip install keplergl
```
The `darribas/gds:2.0` image is based on the Jupyter docker stacks, you can see versions installed [here](https://github.com/darribas/gds_env/blob/master/stack_py.txt).

2. Build the image

```
docker build -t kgl .
```

3. Launch JupyterLab through the container:

```
docker run -p 8888:8888 -v ${PWD}:/home/jovyan/work --rm -ti kgl
```

4. Open a new notebook and import Kepler.gl widget

Capture

Am I missing something?

### PR DESCRIPTION
**Pull request by darribas**
This patch replaces a print statement coded in Python 2 style with its Python 3 compatible equivalent.

### CODE REVIEW

**Comment by darribas** [comment]
The PR should fix issue #579

**Comment by heshan0131** [comment]
Please add commit signoff with

```sh
git commit --amend --signoff

git push --force-with-lease origin fix#579
```

**Comment by darribas** [comment]
I think I've just done it, but let me know if there's any issue, it's the first time I follow this protocol. Thank you very much!

**Comment by darribas** [comment]
Not sure what is failing on some of the tests, the changes relate only to the printing statement on the Jupyter binding...

**Comment by heshan0131** [comment]
You can ignore the netlify build failure for now

**Comment by darribas** [comment]
Cool, let me know if you want me to add/do anything else.

**Pull request merged**
