### PR TITLE
[Housekeeping] Upgrade and run prettier

### PR DESCRIPTION
**Pull request by schnerd**
Kepler.gl has [prettier](https://prettier.io/) configured but it seems like it has not been run across the codebase in a long time. The fact that it exists in the project but is not being actively used can be problematic for contributors – if their editor has the prettier plugin and is set to format on save, they end up with a bunch of formatting changes that add noise alongside their intended change.

This PR does a couple things:

1. Upgrades prettier 
1. Pins prettier version, as recommended by docs
1. Runs it across the codebase to get it back into a pristinely formatted state
1. Adds a `prettier-all` npm script to quickly format all files

I have [a separate PR](https://github.com/schnerd/kepler.gl/pull/1) for adding a pre-commit hook that ensures files stay formatted into the future, even if contributors don't have an editor plugin (this is what the prettier docs recommend). Once the current PR is landed, I can open that PR against master in this repo.

If this type of auto-formatting is _not_ desired, we should remove prettier from the project.

### CODE REVIEW

**Comment by schnerd** [comment]
Travis failures seem unrelated to this branch.

**Comment by heshan0131** [comment]
Could you hold off landing this, It would be hard to rebase, @macrigiuseppe and I have some in-flight PR that are more than a couple hundred lines.

**Comment by schnerd** [comment]
Will hold off 👍

**Comment by johachi-dw** [comment]
Hi, I was just looking through the documentation for guidance regarding coding style. I would love to contribute to the project in the future and think it would be great to have prettier (re-)integrated into the project.

This pull request needs to be updated (the project has grown a lot since January) before merge. I can happily do that unless @schnerd wants to do it.

It would also be great to have the [contribution documentation](https://github.com/keplergl/kepler.gl/tree/master/contributing) updated to state that the project is using Prettier.

**Comment by schnerd** [comment]
@johachi-dw you're welcome to take over this work! though I'll still defer to @heshan0131 and @macrigiuseppe as to whether the timing is right to add this.

**Comment by johachi-dw** [comment]
@heshan0131 and @macrigiuseppe is now a good time to make a pull request like this one?

**Comment by heshan0131** [comment]
Yes please help us update the contribution developer guide about using prettier. 

In terms of actually running prettier. Both Giuseppe and I have major PRs that would be pretty hard to rebase once master is updated with new code style. If you can create a PR without running prettier. I would make sure to do it once our Large PR has landed...

**Pull request closed without merging**
