### PR TITLE
Make keplergl-jupyter work with JupyterLab 3

### PR DESCRIPTION
**Pull request by bergkvist**
Fixes https://github.com/keplergl/kepler.gl/issues/1390

### CODE REVIEW

**Review by heshan0131 — APPROVED** [review]

**Comment by heshan0131** [comment]
Thanks, will publish a new version

**Comment by kyri-petrou** [comment]
Very excited for this, thank you very much for it! Is there an ETA for the release?

**Comment by bergkvist** [comment]
I updated the version from 0.2.2 to 0.3.0 without testing whether it worked. Seems like I would have also needed to change the version here:
https://github.com/keplergl/kepler.gl/blob/master/bindings/kepler.gl-jupyter/keplergl/_version.py

**Comment by duongnt** [comment]
@heshan0131 any plan to release this fix?

**Comment by ondrejsv** [comment]
Hi @bergkvist and @heshan0131, I don't want to spam the thread but it's been half a year since the Jupyter 3.0 was released and we cannot use the kepler.gl in this version. When are you planning to release the fix?

**Comment by ondrejsv** [comment]
I see now that a new versions of Kepler.gl and Python keplergl PyPi package (0.3.0) have been released which are compatible with Jupyter Lab 3.0. Thank you.

**Comment by heshan0131** [comment]
Yep, sorry I forgot to reply, keplergl-jupyter@0.3.0 (js module) and keplergl@0.3.0 (python modules) has been published

**Comment by domplicated** [comment]
image
is it working for others?

**Comment by heshan0131** [comment]
does jupyterlab 3 has a special requirement for widget setup? the js module exits on npm
https://www.npmjs.com/package/keplergl-jupyter

**Comment by kyri-petrou** [comment]
I had a similar issue and resolved it by going through the steps below:

- Uninstalled both the python and npm (labextension) packages
- Added `MapboxAccessTokenJupyter=<YOUR MAPBOX API TOKEN>` to envvars
- Reinstalled and rebuilt keplergl

I'm not sure if it was the absence of the mapboxapi key during build or during runtime that fixed it (or if this is related at all) but I had this issue on 2 machines and both times it worked afterwards.

Also, make sure that the envvar is present when you run the code in Jupyter. If in doubt, just add this to the cell running the code:

``` python
%env MapboxAccessTokenJupyter=<YOUR TOKEN>
```

**Comment by domplicated** [comment]
hmm, so far I cannot get a working version. working with docker to get it completely separated from local systen anomalies.

**Dockerfile**
`FROM nikolaik/python-nodejs:python3.8-nodejs15
LABEL maintainer "NAME <EMAIL>"


WORKDIR /code
ADD . .

RUN export MapboxAccessTokenJupyter="A_VALID_TOKEN"

COPY requirements.txt /
RUN pip install -r /requirements.txt

RUN jupyter labextension install keplergl-jupyter
RUN jupyter labextension enable keplergl-jupyter
RUN jupyter lab build

EXPOSE 8666
CMD jupyter lab --ip=0.0.0.0 --port 8666 --allow-root
`

**requirements.txt**
`jupyterlab==3.0.16
jupyterlab_widgets==1.0.0
keplergl==0.3.0`

**Comment by ondrejsv** [comment]
Yes, I got it working in JupyterLab 3.0 without problems:

JupyterLab v3.0.16
keplergl-jupyter v0.3.0 enabled ok

image

**Comment by domplicated** [comment]
interesting. any particular order of install? which os?

**Comment by ondrejsv** [comment]
No particular installation order.

image

**Pull request merged**
