### PR TITLE
[Feat]Support Zoom to layer in layer panel

### PR DESCRIPTION
**Pull request by liuwo23**
Add a zoomtolayer PanelAction in the component of layer-panel-header. (The icon is temporarily using filterFunnel, and a scaling icon will need to be designed later)，Then, import MapStateActions.fitBounds in the parent components and write function **onZoomToLayer**：`    _zoomToLayer: MouseEventHandler = e => {
      e?.stopPropagation();
      const bounds = this.props.layer?.meta?.bounds;
      bounds && this.props.zoomToLayer(bounds);
    };
`
Support #2446

### CODE REVIEW

**Comment by liuwo23** [comment]
> @liuwo2 Thanks for the PR. I enabled CI, seems some tests are failing. Also to pass the DCO bullet you need to sign your commit `git ci --signoff`

emmm, I will attempt to resubmit and fix it.

**Review by ibgreen — APPROVED** [review]

**Comment by ibgreen** [comment]
@liuwo23 Apologies for the delay, this is approved and will be landed as soon as the CI tests are green.

**Comment by liuwo23** [comment]
> @liuwo23 Apologies for the delay, this is approved and will be landed as soon as the CI tests are green.

**Comment by liuwo23** [comment]
> @liuwo23 Apologies for the delay, this is approved and will be landed as soon as the CI tests are green.

I recommit, and replace the zoomtolayer's icon.

**Comment by liuwo23** [comment]
> @liuwo23 Apologies for the delay, this is approved and will be landed as soon as the CI tests are green.

The tests turned green. What else needs to be passed?

**Comment by ibgreen** [comment]
> The tests turned green. What else needs to be passed?

Thanks for the contribution. 

PS - Our goal is to start pushing for doc updates together with PR, but we do have a big backlog of documentation and release notes, so maybe there is no obvious place for you to document this.

**Pull request merged**
