### PR TITLE
[WIP] [Feat] Multidataset filters

### PR DESCRIPTION
**Pull request by macrigiuseppe**
This implements #768 
Signed-off-by: Giuseppe Macri <gmacri@uber.com>

### CODE REVIEW

**Comment by scivm** [comment]
How is this change going?  Was trying to use it to model different medical codes each in own csv in time series.   Was using the branch version but did not see any difference.   Selecting "+ Add data source" did not do anything.  This will be a good enhancement.

**Comment by scivm** [comment]
kepler

**Comment by macrigiuseppe** [comment]
@scivm this feature is currently a WIP (work in progress) and updates will be posted as soon as they are ready

**Comment by monikasaran** [comment]
Hi @macrigiuseppe ,
This is a really cool feature and will be a great help for me. Is this PR ready to use?  Can you please share the update on this? 
Thank you so much in advance.

**Comment by monikasaran** [comment]
@macrigiuseppe , If you can help in anyway it will be really appreciated.
I will try to explain my problem as simple as possible.

1. I am working to visualise supply chain on kepler gl.
2. The entities involved: Store address, customer address, Van trip routes
3. One store can deliver packages to multiple customers. Multiple Van can pick the packages from single store.
4. Use case is to be able to filter based on store numbers along with the ability to show details of each and every entity(customer address details and route details) on hover tooltip.

Approaches till now:
- I have tried to populate the data in a single dataset to make the filter work, but the render explodes because it's millions of records we are talking about.
- If I try to reduce the record by making collection of customer address against a single store then details related to the customer(hover tooltip) is impossible to show.
- If I create different datasets for all three, then it is impossible to filter across datasets where store acts as a primary key.

I am in a very rough position now. Let me know if any kind of clarification is required.
Thanks in advance.

**Comment by macrigiuseppe** [comment]
@monikasaran this feature is currently on hold. Before moving to multi dataset filter we are going to restructure filters in order to be more extensible. Unfortunately we don't have an timeline for the new feature

**Pull request closed without merging**
