### PR TITLE
Add GeoArrow to supported formats docs

### PR DESCRIPTION
**Pull request by Danysan1**
Since GeoArrow support has been added in 3.0, this change adds GeoArrow to the supported formats documentation

### CODE REVIEW

**Comment by lixun910** [comment]
Thanks @Danysan1! 
Can you also help to add GeoArrow docs in `Polygon` Layer page? 
https://github.com/keplergl/kepler.gl/blob/de8cb971c8363757fb4bc160cb5e0e76c37d7d07/docs/user-guides/c-types-of-layers/e-polygon.md#L3

**Comment by Danysan1** [comment]
I tried updating it, but I'm not familiar with the codebase and which features changed since the docs were written, so look carefully.

Also, I don't understand what this section refers to:

> A path GeoJSON layer can display data like trip routes or contours. Stroke color can be set with a numerical field.

No "Path" layer type exists and in the Polygon layer type there is no "Path" option

**Review by ibgreen — APPROVED** [review]

**Comment by ibgreen** [comment]
@Danysan1 This is approved and will be landed as soon as the CI tests are green.

**Comment by Danysan1** [comment]
The checks were blocked because I forgot to sign-off the last commit, I amended it adding the Signed-off-by

**Pull request merged**
