### PR TITLE
[Bug] Fix 12350 format in tooltip

### PR DESCRIPTION
**Pull request by b2kdaman**
Somehow formatting for 12350 was faulty and misleading from the start

### CODE REVIEW

**Comment by b2kdaman** [comment]
@macrigiuseppe @heshan0131

**Comment by heshan0131** [comment]
As a best practice, can you please create an issue first before creating a PR next time? An issue can be searched in the future and more people can contribute to the discussion

I think the misleading part is the label not the formatted itself. I would not change the ` .4r`, rather update the label. A format once created should behave the same for backward compatibility. So that people's saved map will show the same tooltip even when the software is updated.

the `.4r` does exactly what it should do: rounds to 4 significant digits so that `12345 -> 12350`,  let's use `12345 -> 12350` as label instead of `12350`

One improvement you can make is add `~` and make it `.4~r`  so it trims the empty 0s 

```
0.1 -> 0.1 (instead of 0.100)

```

**Comment by b2kdaman** [comment]
I would not change the .4r
OR
One improvement you can make is add ~ and make it .4~r so it trims the empty 0s
So which one is it?
.4~r would break compatibility. Seems like our "fixes" doesn't really common use cases @thunter

**Comment by b2kdaman** [comment]
> As a best practice, can you please create an issue first before creating a PR next time? An issue can be searched in the future and more people can contribute to the discussion
Yes you're right. I thought that it would be small fixes that would not fire such a discussion 🤣 My bad.

**Comment by b2kdaman** [comment]
@heshan0131 please review

**Comment by b2kdaman** [comment]
@heshan0131 ?

**Review by heshan0131 — APPROVED** [review]

**Pull request merged**
